<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineRepository extends EntityRepository
{
}
