app_homepage:
    pattern:  /
    defaults: { _controller: App:Cheeses:index }

index_cheeses:
    pattern:  /cheeses
    defaults: { _controller: App:Cheeses:index }

new_cheese:
    pattern:  /cheeses/new
    defaults: { _controller: App:Cheeses:new }

create_cheese:
    pattern:  /cheeses/create
    defaults: { _controller: App:Cheeses:create }

index_cheeses_milk:
    pattern:  /milk/{milk}
    defaults: { _controller: App:Cheeses:indexMilk }

index_cheeses_region:
    pattern:  /region/{region}
    defaults: { _controller: App:Cheeses:indexRegion }

show_cheese:
    pattern: /cheeses/{name}
    defaults: { _controller: App:Cheeses:show }

rate_cheese:
    pattern: /cheese/{name}/rate/{score}
    defaults: { _controller: App:Cheeses:rate }
